### ISSUE TITLE
Update to HomeBridge 1.3 breaks plugin due to 1-character Model number

### ISSUE THREAD

**Issue by MichelRabozee** [QuickSander/homebridge-mieleathome#17]
Hello,
I updated Homebridge to 1.3 this morning (I was on latest 1.2.x). Visibly there are a lot of supplemental checks... and the single digit model number is not well appreciated. I suggest to prepend some string like "MieleDeviceModel-" to the Model 1-digit returned by Miele API (which seems empty in my case BTW).

```
[20/02/2021 11:29:31] [homebridge-mieleathome] This plugin threw an error from the characteristic 'Model': Error: [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory. Ignoring new value.
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:38)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:632:24)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2127:22)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1355:24)
    at _loop_1 (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:601:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:450:21
    at new Promise (<anonymous>)
    at Service.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:549:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1034:72
    at Array.map (<anonymous>)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1034:49) See https://git.io/JtMGR for more info.
```

**Comment by QuickSander** [comment]
Thanks. In the process of adding experimental fridge support (requires some refactoring here and there), but I will release this earlier with disabled fridge support.

**Comment by QuickSander** [comment]
Could you try v2.5.1 just now published?

**Comment by MichelRabozee** [comment]
Hi, I get the same error, but I think it is due to the fact that the already known appliances are just reloaded from cache ?
What can I do ?

**Comment by QuickSander** [comment]
Yes you are correct, I missed that. You can manually remove the accessoryCache from the homebridge directory.
Or install the newest version in which I update the cache context data with the freshly retrieved data. I hope it helps. Was not able to extensively test the side effects.

**Comment by MichelRabozee** [comment]
I did not delete the cache in order to try the version I knew will be coming ;-)

And: no more error, cached appliances correctly handled ! Proficiat !
