### ISSUE TITLE
Cannot start Homebridge with version 2.0.0 plugin - Missing requirement node-persist

### ISSUE THREAD

**Issue by MichelRabozee** [QuickSander/homebridge-mieleathome#5]
Hello,

I just installed the version 2.0.0. I saw that I needed to modify the Platform name to "Miele@home", however

Config:
```
{
    "bridge": {
        "name": "Corniche Homebridge-Three",
        "username": "[redacted]",
        "port": 51809,
        "pin": "[redacted]"
    },
    "platforms": [
        {
            "name": "Corniche Homebridge-Three Config",
            "port": 8082,
            "auth": "form",
            "theme": "red",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Miele",
            "clientID": "[redacted]",
            "clientSecret": "[redacted]",
            "token": "[redacted]",
            "language": "en",
            "pollInterval": 60,
            "disableStopActionFor": [
                "Washing Machines",
                "Dishwashers"
            ],
            "platform": "Miele@home"
        }
    ],
    "accessories": []
}
```

Log:
```
[25/01/2021 10:04:45] [HB Supervisor] Restarting Homebridge...
[25/01/2021 10:04:45] [HB Supervisor] Starting Homebridge with extra flags: -I
[25/01/2021 10:04:45] [HB Supervisor] Started Homebridge v1.2.5 with PID: 34581
[25/01/2021 10:04:45] Loaded config.json with 0 accessories and 2 platforms.
[25/01/2021 10:04:45] ---
[25/01/2021 10:04:45] Loaded plugin: homebridge-camera-ffmpeg@3.0.3
[25/01/2021 10:04:45] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[25/01/2021 10:04:45] ---
[25/01/2021 10:04:45] Loaded plugin: homebridge-config-ui-x@4.36.0
[25/01/2021 10:04:45] Registering platform 'homebridge-config-ui-x.config'
[25/01/2021 10:04:45] ---
[25/01/2021 10:04:45] Loaded plugin: homebridge-contactnotifier@0.0.6
[25/01/2021 10:04:45] Registering accessory 'homebridge-contactnotifier.ContactNotifier'
[25/01/2021 10:04:45] ---
[25/01/2021 10:04:46] Loaded plugin: homebridge-daikin-local@2021.4.1
[25/01/2021 10:04:46] Registering accessory 'homebridge-daikin-local.Daikin-Local'
[25/01/2021 10:04:46] ---
[25/01/2021 10:04:46] Loaded plugin: homebridge-http-switch@0.5.34
[25/01/2021 10:04:46] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[25/01/2021 10:04:46] ---
[25/01/2021 10:04:46] ====================
[25/01/2021 10:04:46] ERROR LOADING PLUGIN homebridge-mieleathome:
[25/01/2021 10:04:46] Error: Cannot find module 'node-persist'
Require stack:
- /usr/local/lib/node_modules/homebridge-mieleathome/dist/token.js
- /usr/local/lib/node_modules/homebridge-mieleathome/dist/platform.js
- /usr/local/lib/node_modules/homebridge-mieleathome/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-mieleathome/src/token.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[25/01/2021 10:04:46] ====================
[25/01/2021 10:04:46] Loaded plugin: homebridge-outsidetemperature@0.0.2
[25/01/2021 10:04:46] Registering accessory 'homebridge-outsidetemperature.OutsideTemperature'
[25/01/2021 10:04:46] ---
[25/01/2021 10:04:46] Loaded plugin: homebridge-platform-wemo@2.9.1
[25/01/2021 10:04:46] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[25/01/2021 10:04:46] ---
[25/01/2021 10:04:46] Loaded plugin: homebridge-roomba2@1.2.0
[25/01/2021 10:04:46] Registering accessory 'homebridge-roomba2.Roomba2'
[25/01/2021 10:04:46] ---
[25/01/2021 10:04:46] Loaded plugin: homebridge-script2@0.3.0
[25/01/2021 10:04:46] Registering accessory 'homebridge-script2.Script2'
[25/01/2021 10:04:46] ---
[25/01/2021 10:04:46] Loaded plugin: homebridge-sonytvremote@10.1.3
[25/01/2021 10:04:46] Registering accessory 'homebridge-sonytvremote.SonyTV'
[25/01/2021 10:04:46] ---
[25/01/2021 10:04:47] Loaded plugin: homebridge-videodoorbell@0.2.9
[25/01/2021 10:04:47] Registering platform 'homebridge-videodoorbell.Video-doorbell'
[25/01/2021 10:04:47] ---
[25/01/2021 10:04:47] Loaded plugin: homebridge-watervolume@0.0.2
[25/01/2021 10:04:47] Registering accessory 'homebridge-watervolume.WaterVolume'
[25/01/2021 10:04:47] ---
[25/01/2021 10:04:47] Loading 2 platforms...
[25/01/2021 10:04:47] [Corniche Homebridge-Three Config] Initializing config platform...
[25/01/2021 10:04:47] [Corniche Homebridge-Three Config] Running in Service Mode
[25/01/2021 10:04:47] Error loading platform requested in your config.json at position 2
[25/01/2021 10:04:47] Error: The requested platform 'Miele@home' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[25/01/2021 10:04:47] Got SIGTERM, shutting down Homebridge...
```

It seems that there is a requirement not fulfilled (node-persist), even after having installed it (sudo npm install node-persist)

**Comment by MichelRabozee** [comment]
OK, 
I ran several times "sudo npm install node-persist" and now homebridge starts correctly.
I do not know why it did not take the first time... strange.
