### ISSUE TITLE
Remaining duration warning every minute (washing machine)

### ISSUE THREAD

**Issue by StaX91** [QuickSander/homebridge-mieleathome#61]
Log:

[11/27/2021, 6:19:01 PM] [Miele@home] Washing machine: Updating characteristic InUse to 0.
[11/27/2021, 6:19:01 PM] [homebridge-mieleathome] This plugin generated a warning from the characteristic 'Remaining Duration': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

**Comment by cr3ative** [comment]
Mine is also doing this;

```
[01/12/2021, 16:49:42] [Miele@home] Washer dryer: Returning 1 for Active.
[01/12/2021, 16:49:42] [Miele@home] Washer dryer: Returning 0 for InUse.
[01/12/2021, 16:49:42] [Miele@home] Washer dryer: Returning NaN for RemainingDuration.
[01/12/2021, 16:49:42] [homebridge-mieleathome] This plugin generated a warning from the characteristic 'Remaining Duration': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[01/12/2021, 16:49:42] [homebridge-mieleathome] Error: 
    at RemainingDuration.Characteristic.characteristicWarning (C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2074:105)
    at RemainingDuration.Characteristic.validateUserInput (C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1967:16)
    at C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1569:24
    at C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\once.ts:9:18
    at MieleRemainingDurationCharacteristic.get (C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge-mieleathome\src\mieleCharacteristics.ts:50:5)
    at RemainingDuration.emit (events.js:400:28)
    at C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1544:14
    at new Promise (<anonymous>)
    at RemainingDuration.<anonymous> (C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1542:12)
    at step (C:\Users\Media Center\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)
[01/12/2021, 16:49:42] [Miele@home] Washer dryer: Returning 0 for CurrentTemperature.
[01/12/2021, 16:50:12] [Miele@home] Washer dryer: Returning 0 for CurrentTemperature.
[01/12/2021, 16:50:12] [Miele@home] Washer dryer: Returning 1 for Active.
```

**Comment by bsoener** [comment]
me too:

[07/12/2021, 17:12:40] [homebridge-mieleathome] This plugin generated a warning from the characteristic 'Remaining Duration': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[07/12/2021, 17:23:34] [homebridge-mieleathome] This plugin generated a warning from the characteristic 'Remaining Duration': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

**Comment by QuickSander** [comment]
Thanks @cr3ative for the debug logging. I will look into this.

**Comment by QuickSander** [comment]
Does the logging state: "Remaining duration update received" in debug logging? And what did it print?
It is namely not a trivial error and looks more like a race condition between get and update.
I will try to deliver an update which suppresses the null, but that will most likel also cause the remaining duration not to update.

**Comment by QuickSander** [comment]
The new release should help, but I think it still leaves the remaining duration invalid and would need the swagger output for that to debug.

**Comment by StaX91** [comment]
> The new release should help, but I think it still leaves the remaining duration invalid and would need the swagger output for that to debug.

I can confirm that since the update remaining duration works perfectly! No more errors in logs and the duration is valid! Thanks!
