### ISSUE TITLE
Just updated Homebridge UI to v4.50.0 - Miele PlugIn fails to start

### ISSUE THREAD

**Issue by MichelRabozee** [QuickSander/homebridge-mieleathome#70]
Hello,

I just updated Homebridge UI to v4.50.0 - Miele PlugIn (3.5.0) now fails to start

```
[20/07/2022 20:45:45] [Miele] Lave-linge: Initial connection with Miele event server successfully established.
[20/07/2022 20:45:45] [Miele] Lave-linge: Updating characteristic Active to 1.
[20/07/2022 20:45:45] TypeError: Cannot read properties of undefined (reading 'unit')
    at MieleTemperatureUnitCharacteristic.update (/usr/local/lib/node_modules/homebridge-mieleathome/src/mieleCharacteristics.ts:479:32)
    at MieleFridgePlatformAccessory.update (/usr/local/lib/node_modules/homebridge-mieleathome/src/mieleBasePlatformAccessory.ts:185:22)
    at EventSource.<anonymous> (/usr/local/lib/node_modules/homebridge-mieleathome/src/mieleBasePlatformAccessory.ts:102:12)
    at EventSource.emit (node:events:390:28)
    at _emit (/usr/local/lib/node_modules/homebridge-mieleathome/node_modules/eventsource/lib/eventsource.js:257:17)
    at parseEventStreamLine (/usr/local/lib/node_modules/homebridge-mieleathome/node_modules/eventsource/lib/eventsource.js:272:9)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-mieleathome/node_modules/eventsource/lib/eventsource.js:231:11)
    at IncomingMessage.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by QuickSander** [comment]
I'm running 4.50.1 without this issue. Is this still a problem?

**Comment by MichelRabozee** [comment]
Hello,

sorry, as I had no more info and no clue to prevent the issue, I disabled the Miele plug-in, and completely forgot to check again when Homebridge UI was update somewhere in August :-(

I just reenabled the plug-in and effectively, everything works again !

Thank you and sorry again for not having followed up on this matter. I close the issue.

**Comment by MichelRabozee** [comment]
The problem disappeared with the 4.50.1 version of Homebridge UI.
